# Generated by Django 5.2.10 on 2026-02-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
    ]
