# Generated by Django 5.2.11 on 2026-02-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_timetable', '0003_remove_sycoainput_is_lab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FycoInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('theory_credits', models.IntegerField(default=0, help_text='Theory Load (e.g. 5 means 5 hours/week)')),
                ('practical_credits', models.IntegerField(default=0, help_text='Practical Load (2 credits = 1 block of 2 hours)')),
                ('time_constraints', models.TextField(blank=True, help_text='JSON or text description of constraints', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FycoTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(default='ALL', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SycoInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('theory_credits', models.IntegerField(default=0, help_text='Theory Load (e.g. 5 means 5 hours/week)')),
                ('practical_credits', models.IntegerField(default=0, help_text='Practical Load (2 credits = 1 block of 2 hours)')),
                ('time_constraints', models.TextField(blank=True, help_text='JSON or text description of constraints', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SycoTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(default='ALL', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TycoInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('theory_credits', models.IntegerField(default=0, help_text='Theory Load (e.g. 5 means 5 hours/week)')),
                ('practical_credits', models.IntegerField(default=0, help_text='Practical Load (2 credits = 1 block of 2 hours)')),
                ('time_constraints', models.TextField(blank=True, help_text='JSON or text description of constraints', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TycoTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(default='ALL', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SycoAInput',
        ),
        migrations.DeleteModel(
            name='SycoATimetable',
        ),
        migrations.DeleteModel(
            name='SycoBInput',
        ),
        migrations.DeleteModel(
            name='SycoBTimetable',
        ),
        migrations.DeleteModel(
            name='TycoAInput',
        ),
        migrations.DeleteModel(
            name='TycoATimetable',
        ),
        migrations.DeleteModel(
            name='TycoBInput',
        ),
        migrations.DeleteModel(
            name='TycoBTimetable',
        ),
    ]
